### PR TITLE
0.5.0 release: added unique constraint, parse folder cli command

### PR DESCRIPTION
**Pull request by xnuinside**

### CODE REVIEW

**Comment by geob3d** [comment]
Hi @xnuinside 

Once again, this is amazing !

Below are the results from the testing. 

**The following Sql statements work as expected**

```
CREATE TABLE employees (
id SERIAL PRIMARY KEY,
first_name VARCHAR (50),
last_name VARCHAR (50),
birth_date DATE CHECK (birth_date > '1900-01-01'),
joined_date DATE CHECK (joined_date > birth_date),
salary numeric CHECK(salary > 0)
);
CREATE TABLE Persons (
ID int NOT NULL,
LastName varchar(255) NOT NULL,
FirstName varchar(255),
Age int,
City varchar(255),
CONSTRAINT CHK_Person CHECK (Age>=18 AND City='Sandnes')
);
```
**The Alter table statement for check constraint does not work as expected.**
It cuts out some of the values in the check expression. Please see the code below to reproduce the issue.

```
parse_results = DDLParser("""
CREATE TABLE Persons (
ID int NOT NULL,
LastName varchar(255) NOT NULL,
FirstName varchar(255),
Age int,
City varchar(255),
CONSTRAINT CHK_Person CHECK (Age>=18 AND City='Sandnes')
);

ALTER TABLE Persons ADD CHECK (Age>=18 AND City='Sandnes);


""").run()

ic(parse_results)
```

**Suggestion for Alter Table Syntax and Constraints**
I also recommend adding support for following Alter table and add constraint syntax. 

```
ALTER TABLE Persons Add CONSTRAINT ck_person  CHECK (Age>=18 AND City='Sandnes);
Alter Table Persons ADD CONSTRAINT fk_group FOREIGN KEY (id) REFERENCES employees (id); 
```
Please let me know if you need any clarifications on my comments above. 


PS: The work you have done on this project is amazing.

**Comment by xnuinside** [comment]
@geob3d , thank you for testing :) I'm working on fix for alter tables

**Comment by xnuinside** [comment]
@geob3d  I added all cases, that you described upper & released as alpha version to test - 0.5.0a0. PR is also updated. Tomorrow I will add tests & docs. Please, check if you will have a time. And thank you for you help!

**Comment by geob3d** [comment]
HI @xnuinside 

Once again, thank you for all you hard work! I am really love the direction that this project is going so I am more than happy to help in any way that I can. 

I just tested some of the changes and encountered the following:

**The following SQL STATEMENT work in the the updated version:**
```

ALTER TABLE Persons ADD CHECK (Age>=18 AND City='Sandnes');
Alter Table Persons ADD CONSTRAINT fk_group FOREIGN KEY (id) REFERENCES employees (id);

```

**The follow SQL State doest not return any output when added :**
`    Alter Table Persons ADD CONSTRAINT CHK_PersonAge CHECK (Age>=18 AND City='Sandnes');`

Below is the code to reproduce the issue: 
```
from simple_ddl_parser import DDLParser

parse_results = DDLParser("""

    CREATE TABLE Persons (
    ID int NOT NULL,
    LastName varchar(255) NOT NULL,
    FirstName varchar(255),
    Age int,
    City varchar(255),

    );
    Alter Table Persons ADD CONSTRAINT CHK_PersonAge CHECK (Age>=18 AND City='Sandnes');   
""").run()

print(parse_results)
```

**Comment by xnuinside** [comment]
@geob3d  done ) pls check,  0.5.0a1 released

**Comment by xnuinside** [comment]
@geob3d, I added last tests. If all ok - I ready to merge and release version)

**Comment by geob3d** [comment]
Hi @xnuinside 
I ran a couple of tests on the changes and the following code now works as expected.  I believe that that version can now be merged. 
```
from simple_ddl_parser import DDLParser

parse_results = DDLParser("""

    CREATE TABLE Persons (
    ID int NOT NULL,
    LastName varchar(255) NOT NULL,
    FirstName varchar(255),
    Age int,
    City varchar(255),

    );
    Alter Table Persons ADD CONSTRAINT CHK_PersonAge CHECK (Age>=18 AND City='Sandnes');   
""").run()

print(parse_results)
```

I will continue to test the package and make sure that I don't encounter any other missing items. 

This project keeps getting better and better

**Review by geob3d — APPROVED** [review]
All the changes that have been added are working as designed.

**Comment by xnuinside** [comment]
@geob3d  great :) thank you for testing!

**Pull request merged**
