### PR TITLE
feature #218 solve my requirement

### PR DESCRIPTION
**Pull request by dmaresma**
Hi and Happy New Year !
I would like summit to you my contribution to solve the EXTERNAL TABLE and Virtual Column ddl.

Thanks again to initiate and support this project.

#218  issue solver

### CODE REVIEW

**Comment by xnuinside** [comment]
@dmaresma hello again :) and happy new year you too! Thanks for submitting the PR. I see flake 8 issues. In repo there is the pre-commit hooks, you can run ‘pre-commit install’ and ‘pre commit run -- all-files’ to check those issues on local machine

**Comment by xnuinside** [comment]
You solved it faster than I added my comment :)

**Comment by dmaresma** [comment]
My Bad, I introduce regression, by not running all test before, I'm back on the workbench.

**Comment by dmaresma** [comment]
Ta da, it's fixed all tests passed, thanks for your time.

**Comment by xnuinside** [comment]
@dmaresma awesome, thank you! I will release it soon

**Review by xnuinside — APPROVED** [review]

**Comment by xnuinside** [comment]
@dmaresma  released in version 0.31.3 https://pypi.org/project/simple-ddl-parser/

**Pull request merged**
