### PR TITLE
Adding MSSQL / T-SQL  DLL Suport

### PR DESCRIPTION
**Pull request by geob3d**
Hi @xnuinside 

I hope your are doing well. I saw that you made some major enhancements since to those project (FYI this is still amazing). I just wanted to provide this comprehensive query for when you add MS/T SQL  to the parser. You will notice that Postgres and MS SQL have  similar syntaxes . I decided to add this DDL includes almost every TSQL data types. I also included the max sizes for each of the data types. Please feel free to let me know if you have any issues with the query. 

```
CREATE TABLE Persons (
    PersonID int PRIMARY KEY,
    LastName varchar(255),
    FirstName varchar(255),
    Address varchar(255),
    City varchar(255)
);


CREATE TABLE sqlserverlist (

id INT IDENTITY (1,1) PRIMARY KEY, -- NOTE THE IDENTITY (1,1) IS SIMILAR TO serial in postgres - Format for IDENTITY [ (seed , increment) ]
company_id BIGINT ,
primary_id INT FOREIGN KEY REFERENCES Persons(PersonID), -- ADD THIS COLUMN FOR THE FOREIGN KEY
age TINYINT NULL UNIQUE,
days_active SMALLINT NOT NULL,
user_origin_of_birth char(255),
user_account VARCHAR(8000) NOT NULL,
user_first_name VARCHAR(max) NOT NULL,
user_last_name 	VARBINARY(8000) NOT NULL,
user_street NCHAR(400) NULL,
user_city NVARCHAR(4000),
about_user NTEXT NULL,
user_description TEXT,
starting_funds FLOAT(53) NULL,
extra_funds REAL,
current_funds DECIMAL (38,20),
ending_funds SMALLMONEY NOT NULL,
birth_date DATE NOT NULL,
time_of_birth TIME(7),
enrollment_date SMALLDATETIME,
delete_date DATETIME NULL,
create_date DATETIME2(7) NOT NULL,
user_time_zone DATETIMEOFFSET(7),
oder_date date DEFAULT GETDATE(), -- added to demonstrate sql sever Defaults
country varchar(255) DEFAULT 'Sandnes', -- added to demonstrate sql sever Defaults
active bit NULL,
home_size GEOMETRY, -- Sql Server Defaults to Null
user_photo IMAGE, -- Sql Server Defaults to Null
--UNIQUE (id),
CONSTRAINT UC_sqlserverlist_last_name UNIQUE (company_id,user_last_name),
CONSTRAINT CHK_Person_Age_under CHECK (days_active<=18 AND user_city='New York'),
FOREIGN KEY (id) REFERENCES Persons(PersonID),
CONSTRAINT FK_Person_Age_under  FOREIGN KEY (id)REFERENCES Persons(PersonID)
)

-- UNIQUE CONSTRAINTS
ALTER TABLE sqlserverlist ADD UNIQUE (birth_date);
ALTER TABLE sqlserverlist ADD CONSTRAINT UC_Person_ening_funds UNIQUE (current_funds,create_date);
--CHECK CONSTRAINTS
ALTER TABLE sqlserverlist ADD CHECK (starting_funds>=0);
ALTER TABLE sqlserverlist ADD CONSTRAINT CHK_Person_Age CHECK (age >=18 AND user_city='Sandnes');
-- FOREIGN KEY Constraints
ALTER TABLE sqlserverlist ADD FOREIGN KEY (id) REFERENCES Persons(PersonID);
ALTER TABLE sqlserverlist ADD CONSTRAINT FK_PersonOrder4 FOREIGN KEY (id) REFERENCES Persons(PersonID);
-- INDEXES 
CREATE INDEX i1 ON sqlserverlist (extra_funds);
--CREATE CLUSTERED INDEX i2 ON sqlserverlist  (delete_date,create_date); --- This line is commented because TSQL doesnt allow two index on table added as an example
--CREATE UNIQUE INDEX i1 ON t1 (delete_date DESC, create_date ASC, ending_funds  DESC); --- This line is commented because TSQL doesnt allow two index on table added as an example

-- DEFAULTS
ALTER TABLE sqlserverlist ADD CONSTRAINT df_user_street DEFAULT '1 WAY STREET' FOR user_street;
SELECT * FROM #sqlserverlist
```

### CODE REVIEW

**Comment by xnuinside** [comment]
@geob3d hello! why you open a or and not issue?) I’m not sure, because I don’t see any changes

**Comment by geob3d** [comment]
> @geob3d hello! why you open a or and not issue?) I’m not sure, because I don’t see any changes
Hi @xnuinside 

I completely made a mistake by adding my suggestion to the pr. I should have been paying more attention before submitting. I had several windows at the time and I just realized what I did. I will move the suggestion to incidents. I am sorry for the error on my part.

**Comment by xnuinside** [comment]
@geob3d, it’s okay :) Sometimes I do similar things just because of hurry up or tiredness

**Comment by xnuinside** [comment]
I will close it because we move it to issues

**Pull request closed without merging**
