### PR TITLE
fix for the issue with column name started with CREATE

### PR DESCRIPTION
**Pull request by xnuinside**

### CODE REVIEW

**Comment by n2ygk** [comment]
Thanks. Are you going to push this one to pypi?

**Comment by n2ygk** [comment]
PS: I've installed it via `git+https://github.com/xnuinside/simple-ddl-parser.git` for now. Works great! Thanks.

**Comment by xnuinside** [comment]
@n2ygk hm) I released it on the morning https://pypi.org/project/simple-ddl-parser/

**Comment by n2ygk** [comment]
Hmm looks like my local nexus pypi mirror is not syncing properly.

**Comment by xnuinside** [comment]
@n2ygk  I have similar issues in project internal PyPi - it updated libraries versions only once in 24 hours, so for example, if in the morning you tried pip install some new version, but 8 hours later was released new - local pypi will ignore it  and get new versions only after 24 hours. At least this is that I see on current project & several times before.

**Pull request merged**
