### PR TITLE
Parse KEY statements within CREATE TABLE statements

### PR DESCRIPTION
**Pull request by cfhowes**
I have DDL with KEY statements as part of the CREATE TABLE statement.  This is a seemingly valid way to indicate an index in SQL.  I created a test case with a sample of the SQL I am working with, and the desired listing of an index.

I do not know the parser grammar all that well - it's possible that while the code works and passes the test cases that my implementation is not technically correct.  Please give me pointers and I'll fix it up.

### CODE REVIEW

**Comment by cfhowes** [comment]
Looks like (after re-reading the contributing guidelines) that I also will need to update README.md and CHANGELOG.txt.  I'll do this if I receive feedback that I'm on the right track here.

**Comment by dmaresma** [comment]
Hi, only update the CHANGELOG, the bash script (`build.sh`) 'll update the README.md, please can I ask you to run the `flake8 .\simple_ddl_parser\` and fix the lint .
Thanks for your contribution.

**Comment by cfhowes** [comment]
Thanks!  Apologies for missing the flake8 check initially.  Should be updated now.

**Comment by xnuinside** [comment]
@cfhowes merge conflict with main branch - need to resolve it. Please, get changes from main branch and re-run tests on your local machine to re-generate parsertab.py with your changes

**Review by xnuinside — APPROVED** [review]
@cfhowes thanks for your PR :) awesome! I will release version with changes little bit later today

**Comment by xnuinside** [comment]
@cfhowes released in version 0.31.3 https://pypi.org/project/simple-ddl-parser/

**Pull request merged**
